name: hermez
description: Hermez native wallet project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+12



environment:
  sdk: ">=2.2.2 <3.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  hermez_plugin:
    path: ../hermez_plugin/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  web3dart: ^1.2.3
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  bip39: ^1.0.3
  bitcoin_flutter: ^2.0.2
  # tweetnacl: ^0.3.2
  pointycastle: ^1.0.2
  hex: ^0.1.2
  flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.5
  camera: ^0.5.7+3
  path_provider: ^2.0.1
  share: ^2.0.1

  web_socket_channel: ^1.1.0
  intl: ^0.17.0
  flutter_spinkit: "^4.1.1+1"
  # firebase_analytics: ^7.1.1
  # firebase_core: ^1.0.2
  # firebase_ml_vision: ^0.11.0
  url_launcher: ^6.0.3
  flutter_hooks: ^0.9.0
  built_value: ^8.0.0
  built_collection: ^5.0.0
  flutter_svg: ^0.17.4
  auto_size_text: ^2.1.0
  grouped_list: ^3.3.0
  local_auth: ^1.1.1
  flutter_windowmanager: ^0.0.2
  clipboard: ^0.1.3

  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  built_value_generator: ^8.0.4
  json_serializable: ^3.2.5
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Intro
    - intro_hermez_logo.png
    # Info
    - info_success.png
    - info_failure.png
    # Biometrics
    - biometrics_fingerprint.png
    - biometrics_face.png
    - face.png
    - fingerprint.png
    - arrow_right.png
    - backup_warning.png
    # Backup
    - info_backup.png
    - info_backup_success.png
    # Remove account
    - remove_account.png
    - remove_account_warning.png
    # Home
    - receive2.png
    - settings2.png
    - home_tab_item.png
    - move.png
    - hermez_logo.png
    - ethereum_logo.png
    - move2.png
    - change_move_enable.png
    - change_move_disable.png

    - view_explorer.png
    - show_recovery_phrase.png
    - change_passcode.png
    - force_withdrawal.png
    - logout.png
    - currency_conversion.png


    - partialERC20ABI.json
    - ERC20ABI.json
    - HermezABI.json
    - WithdrawalDelayerABI.json
    - account.png
    - wallet.png
    - search.png
    - send.png
    - send2.png
    - label.png
    - home.png
    - transfer.png
    - list.png
    - deposit.png
    - deposit2.png
    - add.png
    - warning.png
    - pending.png
    - upload.png
    - arrow_down.png
    - arrows_up_down.png
    - success.png
    - settings.png
    - scan.png
    - withdraw.png
    - withdraw2.png
    - tx_send.png
    - tx_receive.png
    - tx_withdraw.png
    - tx_deposit.png
    - show_explorer.png
    - paste.png
    - disconnect.png
    - force_exit.png
    - qr_code.png
    - explorer.png
    - info.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  # fonts:
    - family: ModernEra
      fonts:
        - asset: fonts/ModernEra-Bold.ttf
        - asset: fonts/ModernEra-ExtraBold.ttf
        - asset: fonts/ModernEra-Medium.ttf
        - asset: fonts/ModernEra-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
